version: '3.6'

services:
  db:
    image: postgres:10.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build: ./api
    command: python /usr/src/api/manage.py runserver 0.0.0.0:8888
    volumes:
      - ./api/:/usr/src/api/
    ports:
      - 8888:8888
    depends_on:
      - db
    environment:
      - SECRET_KEY=please_change_me

  app:
    build: ./app
    command: npm start
    volumes:
      - ./app/:/usr/src/app/
    ports:
      - 5550:5550
    depends_on:
      - api
    environment:
      - SECRET_KEY=please_change_me

volumes:
  postgres_data:
